//! 埋め込みダッシュボード静的アセットの HTTP 配信。
//!
//! build 時に `src/web/static/` を include_dir でバイナリへ埋め込み、
//! パス正規化・MIME 推定を経て配信する。

use axum::{
    body::Body,
    extract::Path as AxumPath,
    http::{header, StatusCode},
    response::{IntoResponse, Response},
};
use include_dir::{include_dir, Dir, File};
use mime_guess::MimeGuess;

static DASHBOARD_ASSETS: Dir = include_dir!("$CARGO_MANIFEST_DIR/src/web/static");
const DASHBOARD_INDEX: &str = "index.html";

// Force rebuild when embedded dashboard/playground assets change.
// The file is generated by `llmlb/build.rs`.
const _DASHBOARD_ASSETS_BUILD_STAMP: &str = include_str!(concat!(
    env!("OUT_DIR"),
    "/dashboard_assets_build_stamp.txt"
));

pub(super) async fn serve_dashboard_index() -> Response {
    embedded_dashboard_response(DASHBOARD_INDEX)
}

pub(super) async fn serve_dashboard_asset(AxumPath(request_path): AxumPath<String>) -> Response {
    let normalized = normalize_dashboard_path(&request_path);
    match normalized {
        Some(path) => embedded_dashboard_response(&path),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

fn embedded_dashboard_response(path: &str) -> Response {
    match DASHBOARD_ASSETS.get_file(path) {
        Some(file) => file_response(file),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

fn file_response(file: &File<'_>) -> Response {
    let mime = MimeGuess::from_path(file.path())
        .first_or_octet_stream()
        .to_string();
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, mime)
        .body(Body::from(file.contents().to_vec()))
        .expect("failed to build embedded dashboard response")
}

fn normalize_dashboard_path(request_path: &str) -> Option<String> {
    let trimmed = request_path.trim_matches('/');
    if trimmed.is_empty() {
        return Some(DASHBOARD_INDEX.to_string());
    }
    if trimmed.contains("..") || trimmed.contains('\\') {
        return None;
    }
    Some(trimmed.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- normalize_dashboard_path tests ---

    #[test]
    fn test_normalize_dashboard_path_empty() {
        assert_eq!(
            normalize_dashboard_path(""),
            Some(DASHBOARD_INDEX.to_string())
        );
    }

    #[test]
    fn test_normalize_dashboard_path_just_slashes() {
        assert_eq!(
            normalize_dashboard_path("/"),
            Some(DASHBOARD_INDEX.to_string())
        );
        assert_eq!(
            normalize_dashboard_path("///"),
            Some(DASHBOARD_INDEX.to_string())
        );
    }

    #[test]
    fn test_normalize_dashboard_path_valid_file() {
        assert_eq!(
            normalize_dashboard_path("assets/index.js"),
            Some("assets/index.js".to_string())
        );
    }

    #[test]
    fn test_normalize_dashboard_path_strips_slashes() {
        assert_eq!(
            normalize_dashboard_path("/assets/style.css/"),
            Some("assets/style.css".to_string())
        );
    }

    #[test]
    fn test_normalize_dashboard_path_rejects_dotdot() {
        assert_eq!(normalize_dashboard_path("../etc/passwd"), None);
        assert_eq!(normalize_dashboard_path("assets/../../../etc/passwd"), None);
    }

    #[test]
    fn test_normalize_dashboard_path_rejects_backslash() {
        assert_eq!(normalize_dashboard_path("assets\\evil.js"), None);
    }

    #[test]
    fn test_normalize_dashboard_path_normal_subdirectory() {
        assert_eq!(
            normalize_dashboard_path("assets/js/main.js"),
            Some("assets/js/main.js".to_string())
        );
    }

    #[test]
    fn test_normalize_dashboard_path_single_file() {
        assert_eq!(
            normalize_dashboard_path("favicon.ico"),
            Some("favicon.ico".to_string())
        );
    }
}
